Day1/urls.py
from django.contrib import admin
from django.urls import path ,include
from staff import views 

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('student/', include('student.urls')),
    # path('staff/', include('staff.urls')),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    # path('register/', views.register, name='register'),
    # path('reports/', include('reports.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('students.urls')),
    path('staff/', include('staff.urls')),
    path('reports/', include('reports.urls')),
    path('', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

students/urls.py
from django.contrib import admin  
from django.urls import path  
from . import views 
# urlpatterns = [ 
#     path('list',views.list),
#     path('insert',views.insert),
#     path('update',views.update),
#     path('delete',views.delete),
#     ##
#     path('', views.student_list, name='student_list'),
#     path('<int:id>/', views.student_detail, name='student_detail'),
#     path('new/', views.student_create, name='student_create'),
#     path('<int:id>/edit/', views.student_update, name='student_update'),
#     path('<int:id>/delete/', views.student_delete, name='student_delete'),
#                ]
from django.urls import path
from .views import StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView
urlpatterns = [
    # path('', views.all_std, name="all_std"),
    # path('insert/', views.insert),
    # path('update/<int:std_id>/', views.update, name='update_student'),
    # path('delete/<int:std_id>/', views.delete, name='delete_student')
    path('', StudentListView.as_view(), name='student_list'),
path('insert/', StudentCreateView.as_view(), name='student_insert'),
path('update/int:pk/', StudentUpdateView.as_view(), name='student_update'),
path('delete/int:pk/', StudentDeleteView.as_view(), name='student_delete'),
]

students/models.py
from django.db import models
from staff.models import Staff

class Student(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    city = models.CharField(max_length=100, null=True)
    supervisor = models.ForeignKey(Staff, on_delete=models.CASCADE, null=True)

students/views.py
# from django.shortcuts import render
# from django.shortcuts import render, redirect  
# from django.http import HttpResponseRedirect, HttpResponse
# # Create your views here.
# def list(r):   
#     return HttpResponse ('Here are your students')  

# def insert(request):  
#     return render(request, 'insertstudent.html')  

# def update(request):    
#     return render(request, 'updatestudent.html') 

# def delete(r):   
#     return redirect("/student/list")  

# def index(request): #view for / 
#  return HttpResponseRedirect(“/posts”) 
 
# def get_posts(request): #view for /posts 
#  return HttpResponse (“Here are your posts”)


# from django.shortcuts import render, get_object_or_404, redirect
# from .models import Student
# from .forms import StudentForm

# def student_list(request):
#     students = Student.objects.all()
#     return render(request, '../templates/studentlist.html', {'students': students})

# def student_detail(request, id):
#     student = get_object_or_404(Student, id=id)
#     return render(request, 'studentdetail.html', {'student': student})

# def student_create(request):
#     if request.method == 'POST':
#         form = StudentForm(request.POST)
#         if form.is_valid():
#             student = form.save()
#             return redirect('student_detail', id=student.id)
#     else:
#         form = StudentForm()
#     return render(request, 'studentform.html', {'form': form})

# def student_update(request, id):
#     student = get_object_or_404(Student, id=id)
#     if request.method == 'POST':
#         form = StudentForm(request.POST, instance=student)
#         if form.is_valid():
#             student = form.save()
#             return redirect('student_detail', id=student.id)
#     else:
#         form = StudentForm(instance=student)
#     return render(request, 'studentform.html', {'form': form})

# def student_delete(request, id):
#     student = get_object_or_404(Student, id=id)
#     student.delete()
#     return redirect('student_list')
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Student
from staff.models import Staff

# def all_std(req):
#     students = Student.objects.all()
#     return render(req, 'student/std_list.html', {'students': students})

# def insert(req):
#     if req.method == 'POST':
#         name = req.POST.get('name')
#         age = req.POST.get('age')
#         city = req.POST.get('city')
#         supervisor_id = req.POST.get('supervisor')
#         supervisor = Staff.objects.get(id=supervisor_id)
#         student = Student(name=name, age=age, city=city, supervisor=supervisor)
#         student.save()
#         return redirect('/student/')
#     supervisors = Staff.objects.all()
#     return render(req, 'student/std_insert.html',{'supervisors': supervisors})

# def update(req,std_id):
#     student = get_object_or_404(Student, id=std_id)
#     if req.method == 'POST':
#         name = req.POST.get('name')
#         age = req.POST.get('age')
#         city = req.POST.get('city')
#         supervisor_id = req.POST.get('supervisor')
#         supervisor = Staff.objects.get(id=supervisor_id)
#         student.name = name
#         student.age = age
#         student.city = city
#         student.supervisor = supervisor
#         student.save()
#         return redirect('/student/')

#     supervisors = Staff.objects.all()
#     return render(req, 'student/std_update.html', {'student': student, 'supervisors': supervisors})



# def delete(req,std_id):
#     student = get_object_or_404(Student, id=std_id)
#     student.delete()
#     return redirect('/student/')


from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Student, Staff

class StudentListView(ListView):
    model = Student
    template_name = 'student/std_list.html'
    context_object_name = 'students'

class StudentCreateView(CreateView):
    model = Student
    template_name = 'student/std_insert.html'
    fields = ['name', 'age', 'city', 'supervisor']
    success_url = reverse_lazy('student_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['supervisors'] = Staff.objects.all()
        return context

class StudentUpdateView(UpdateView):
    model = Student
    template_name = 'student/std_update.html'
    fields = ['name', 'age', 'city', 'supervisor']
    success_url = reverse_lazy('student_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['supervisors'] = Staff.objects.all()
        return context

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('student_list')



templates/student/std_insert.html
<!-- students/add_student.html -->
{% extends 'base.html' %}

{% block title %}Add Student{% endblock %}

{% block content %}
<div style="width:500px">
    <h1 class="mb-5 text-center">Add Student</h1>
<form method="post" class="form form-control">
    {% csrf_token %}
    <label class="form-label" for="id_name">Name:</label>
    <input class="form-control " type="text" name="name" id="id_name">
    <br>
    <label  class="form-label" for="id_age">Age:</label>
    <input class="form-control " type="number" name="age" id="id_age">
    <br>
    <label class="form-label" for="id_city">City:</label>
    <input class="form-control " type="text" name="city" id="id_city">
    <br>
     <label class="form-label" for="id_supervisor">Supervisor:</label>
    <select class="form-control " name="supervisor" id="id_supervisor">
        {% for supervisor in supervisors %}
        <option value="{{ supervisor.id }}">{{ supervisor.name }}</option>
        {% endfor %}
    </select>
    <div class="d-flex justify-content-center mt-2">
        <button type="submit" class="btn btn-success ms-auto">Add</button>
    </div>
</form>

</div>
{% endblock %}

templates/student/std_list.html
<!-- child.html -->
{% extends 'base.html' %}

{% block title %}
    My Child Page
{% endblock %}

{% block content %}
   <div class="d-flex flex-column" style="width:70%">
        <h1 class="text-center mb-5">All Students</h1>

<table class="table">
    <thead class="text-center">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>City</th>
            <th>Supervisor</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        <tr>
            <td>{{ student.name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.city }}</td>
            <td>{{ student.supervisor.name }}</td>
            <td class="d-flex flex-row justify-content-center">
                <a href="{% url 'update_student' student.id %}" class="mx-3 btn btn-warning">Update</a>
                <form action="{% url 'delete_student' student.id %}"  method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

   </div>
{% endblock %}

templates/student/std_update.html
<!-- child.html -->
{% extends 'base.html' %}

{% block title %}
    My Child Page
{% endblock %}

{% block content %}
  <div style="width:500px">
       <h1 class="text-center mb-5">Update Student</h1>

<form method="post"  class="form form-control">
    {% csrf_token %}
    <label  class="form-label" for="id_name">Name:</label>
    <input  class="form-control" type="text" name="name" id="id_name" value="{{ student.name }}">
    <br>
    <label  class="form-label" for="id_age">Age:</label>
    <input  class="form-control" type="number" name="age" id="id_age" value="{{ student.age }}">
    <br>
    <label  class="form-label" for="id_city">City:</label>
    <input   class="form-control" type="text" name="city" id="id_city" value="{{ student.city }}">
    <br>
    <label  class="form-label" for="id_supervisor">Supervisor:</label>
    <select   class="form-control" name="supervisor" id="id_supervisor">
        {% for supervisor in supervisors %}
        <option value="{{ supervisor.id }}" {% if student.supervisor.id == supervisor.id %}selected{% endif %}>{{ supervisor.name }}</option>
        {% endfor %}
    </select>
    <br>
     <div class="d-flex justify-content-center mt-2">
        <button type="submit" class="btn btn-success ms-auto">Update</button>
    </div>
</form>
  </div>
{% endblock %}